---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mlops-dev
  region: us-east-2
  version: "1.19"
  tags:
    owner: eSimplicity
    project: mlops
    environment: dev

availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]

nodeGroups:
  - name: cpu-workers-nodegroup
    instanceType: 
    labels:
      node-class: cpu-workloads
      nodegroup-type: cpu-workloads
      kubernets.io/role: cpu-workloads-worker
    tags:
      owner: eSimplicity
      usage: mlops
      environment: dev
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: OnDemand
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "false"
      k8s.io/cluster-autoscaler/node-template/label/gpu-count: "0"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-23: "owned"
    desiredCapacity: 2
    minSize: 0
    maxSize: 10
    volumeSize: 100
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        appMesh: true
        appMeshPreview: true
        albIngress: true
        cloudWatch: true
    ssh:
      allow: true
      publicKeyPath: /Users/sergey.semichev/.ssh/mlops-eks.pub

  - name: gpu-workers-nodegroup
    instanceType: p2.xlarge
    # Make sure the availability zone here is one of cluster availability zones.
    availabilityZones: ["us-east-2b"]
    labels:
      node-class: gpu-workloads
      nodegroup-type: gpu-workloads
      kubernets.io/role: gpu-workloads-worker
    tags:
      owner: eSimplicity
      usage: mlops
      environment: dev
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: OnDemand
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "false"
      k8s.io/cluster-autoscaler/node-template/label/gpu-count: "0"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-23: "owned"
    desiredCapacity: 0
    minSize: 0
    maxSize: 5
    volumeSize: 100
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        appMesh: true
        appMeshPreview: true
        albIngress: true
        cloudWatch: true
    ssh:
      allow: true
      publicKeyPath: /Users/sergey.semichev/.ssh/mlops-eks.pub

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]